### PR TITLE
Add Crick and N4BI samples

### PR DESCRIPTION
**Pull request by joshmoore**

### CODE REVIEW

**Comment by joshmoore** [comment]
See https://deploy-preview-54--euphonious-mochi-664405.netlify.app/?csv=https://raw.githubusercontent.com/ome/ome2024-ngff-challenge/0e14f3376c70a3c524a08bc79d367ec14b549b1a/samples/ngff_samples.csv

image

Minor issues:
* thumbnails (for bf2raw collections?) aren't loading
* CSV URLs ending with `"/"` fail
* top-level CSV of the current branch isn't used

But those are all outside of this PR.

cc: @will-moore @constantinpape @folterj @JThoennissen

**Comment by joshmoore** [comment]
with #56 merged, getting this in, then we can re-arrange with the hierarchy browser later.

**Comment by will-moore** [comment]
NB: https://radosgw.public.os.wwu.de/n4bi-wp1/challenge/n4bi.csv links to https://radosgw.public.os.wwu.de/n4bi-fzj/ome2024-ngff-challenge/fzj.csv which contains https://radosgw.public.os.wwu.de/n4bi-fzj/ome2024-ngff-challenge/BigBrain.zarr which is Not Found 404.
I'll remove that from our copy of `fzj.csv`...

**Comment by JThoennissen** [comment]
Sorry, I didn't manage to get the conversion working in time for this volume ... Thank you for removing!

**Comment by will-moore** [comment]
NB: I made local copies of `crick.csv` and `n4bi.csv` in order to add extra columns needed in #53.
See https://github.com/ome/ome2024-ngff-challenge/blob/main/samples/crick.csv and https://github.com/ome/ome2024-ngff-challenge/blob/main/samples/n4bi.csv

The script used to add these extra columns is at https://github.com/ome/ome2024-ngff-challenge/blob/main/samples/load_zarr_stats.py

**Comment by joshmoore** [comment]
Ok. I'm deleting my CSVs files from the S3 bucket then to avoid confusion.

**Pull request merged**
