### PR TITLE
Add lin_samples.csv

### PR DESCRIPTION
**Pull request by joshmoore**
Based on https://github.com/ome/ome2024-ngff-challenge/pull/54#issuecomment-2430293833, @tstoeter I'm moved the lin.csv file here since this was causing our sync issue. You might want to remove your copy to avoid confusion.

@will-moore, can you look over this?

### CODE REVIEW

**Comment by will-moore** [comment]
I ran `python load_zarr_stats.py lin_samples.csv` on a local copy of the csv to give me the extra columns for the viewer:

<details><summary>lin_output.csv</summary>
```
url,written,written_human_readable,shape,shards,chunks,dimension_names,license,name,description,organismId,fbbiId
https://radosgw.public.os.wwu.de/ta3-bucket/150715_DBE_Drosi_CherryCAAX_nSybGal4/L3_nsybG4xcherryCAAXmerged.ims.zarr,2217337815,2.1G,"1,1,707,4127,12497","1,1,1,2048,2048","1,1,1,256,256","t,c,z,y,x",https://creativecommons.org/licenses/by/4.0/,,,NCBI:txid7227,obo:FBbi_00000369
https://radosgw.public.os.wwu.de/ta3-bucket/150421_DBE_L3_C155xCherryDlgS97/stiched_1.ims.zarr,4846235826,4.6G,"1,2,367,6097,9665","1,1,1,2048,2048","1,1,1,256,256","t,c,z,y,x",https://creativecommons.org/licenses/by/4.0/,dataset name,dataset description,NCBI:txid7227,obo:FBbi_00000369
https://radosgw.public.os.wwu.de/ta3-bucket/2014_07_04_Drosi_hole_larve_GFP/Larve_2_20x095_Z1_4096_BAPP_with_cslip.lif.zarr,1631354605,1.6G,"1,1,316,4096,4096","1,1,1,2048,2048","1,1,1,256,256","t,c,z,y,x",https://creativecommons.org/licenses/by/4.0/,,,NCBI:txid7227,obo:FBbi_00000369
https://radosgw.public.os.wwu.de/ta3-bucket/2014_07_04_Drosi_hole_larve_GFP/Larve_2_20x095_Z2_2048_BAPP_wo_cslip.lif.zarr,1127129565,1.1G,"1,2,155,2048,2048","1,1,1,2048,2048","1,1,1,256,256","t,c,z,y,x",https://creativecommons.org/licenses/by/4.0/,,,NCBI:txid7227,obo:FBbi_00000369
https://radosgw.public.os.wwu.de/ta3-bucket/150709_DBE_Drosi_CherryCAAX_OK371/DBE_Drosi_L3_OK371xcherryCAAX_merged.ims.zarr,5541964433,5.2G,"1,1,701,4224,15308","1,1,1,2048,2048","1,1,1,256,256","t,c,z,y,x",https://creativecommons.org/licenses/by/4.0/,dataset name,dataset description,NCBI:txid7227,obo:FBbi_00000369
https://radosgw.public.os.wwu.de/ta3-bucket/140721_Drosi_whole_larve_BABB/Drosi_holeLarve_20x095_2048_Z1.lif.zarr,29151733841,28G,"1,1,1,3912,849","1,1,1,2048,2048","1,1,1,256,256","t,c,z,y,x",https://creativecommons.org/licenses/by/4.0/,dataset name,dataset description,NCBI:txid7227,obo:FBbi_00000369
https://radosgw.public.os.wwu.de/ta3-bucket/Larvae_2_10x_Z1_25_2048.lif.zarr,9860876320,9.2G,"1,1,490,2048,2048","1,1,1,2048,2048","1,1,1,256,256","t,c,z,y,x",https://creativecommons.org/licenses/by/4.0/,,,NCBI:txid7227,obo:FBbi_00000369
https://radosgw.public.os.wwu.de/ta3-bucket/Drosi_Larvae_Tiles_2.lif.zarr,9731243347,9.1G,"1,1,525,4096,4096","1,1,1,2048,2048","1,1,1,256,256","t,c,z,y,x",https://creativecommons.org/licenses/by/4.0/,,,NCBI:txid7227,obo:FBbi_00000369
https://radosgw.public.os.wwu.de/ta3-bucket/a114.zarr,37860247330,36G,"1,2,4065,2048,2048","1,1,1,2048,2048","1,1,1,256,256","t,c,z,y,x",https://creativecommons.org/licenses/by/4.0/,Rat brain,Rat brain cleared using 3DISCO protocol and imaged using light sheet microscopy.,obo:NCBITaxon_10117,obo:OBI_0003098
https://radosgw.public.os.wwu.de/ta3-bucket/a115.zarr,35816681857,34G,"1,2,3996,2048,2048","1,1,1,2048,2048","1,1,1,256,256","t,c,z,y,x",https://creativecommons.org/licenses/by/4.0/,Rat brain,Rat brain cleared using 3DISCO protocol and imaged using light sheet microscopy.,obo:NCBITaxon_10117,obo:OBI_0003098
```
</summary>

Then served this copy and opened in the samples viewer, but I'm seeing no thumbnails due to CORS issues for all the chunks. Same in vizarr - metadata (zarr.json) loads OK but no chunks:

Screenshot 2024-10-23 at 08 56 30

**Comment by joshmoore** [comment]
Fixed CORS and pushed stats, @will-moore: https://ome.github.io/ome2024-ngff-challenge/?csv=https://raw.githubusercontent.com/joshmoore/ome2024-ngff-challenge/lin-samples/samples/lin_samples.csv is looking better. Merging.

**Comment by joshmoore** [comment]
Strike that: my push failed?! (conference network)

```
ssh_dispatch_run_fatal: Connection to 140.82.121.4 port 22: Operation timed out
```

**Comment by joshmoore** [comment]
d56738202c759248b29b5697774c51c72bd0cf4b pushed

**Pull request merged**
